// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: android_proto.proto

package go_android_utils

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AndroidVersion int32

const (
	AndroidVersion_AndroidVersion_NONE AndroidVersion = 0
	AndroidVersion_V4_0                AndroidVersion = 15
	AndroidVersion_V4_1                AndroidVersion = 16
	AndroidVersion_V4_2                AndroidVersion = 17
	AndroidVersion_V4_3                AndroidVersion = 18
	AndroidVersion_V4_4                AndroidVersion = 19
	AndroidVersion_V4_4W               AndroidVersion = 20
	AndroidVersion_V5_0                AndroidVersion = 21
	AndroidVersion_V5_1                AndroidVersion = 22
	AndroidVersion_V6_0                AndroidVersion = 23
	AndroidVersion_V7_0                AndroidVersion = 24
	AndroidVersion_V7_1                AndroidVersion = 25
	AndroidVersion_V8_0                AndroidVersion = 26
	AndroidVersion_V8_1                AndroidVersion = 27
	AndroidVersion_V9_0                AndroidVersion = 28
	AndroidVersion_V10_0               AndroidVersion = 29
	AndroidVersion_V11_0               AndroidVersion = 30
	AndroidVersion_V12_0               AndroidVersion = 31
)

// Enum value maps for AndroidVersion.
var (
	AndroidVersion_name = map[int32]string{
		0:  "AndroidVersion_NONE",
		15: "V4_0",
		16: "V4_1",
		17: "V4_2",
		18: "V4_3",
		19: "V4_4",
		20: "V4_4W",
		21: "V5_0",
		22: "V5_1",
		23: "V6_0",
		24: "V7_0",
		25: "V7_1",
		26: "V8_0",
		27: "V8_1",
		28: "V9_0",
		29: "V10_0",
		30: "V11_0",
		31: "V12_0",
	}
	AndroidVersion_value = map[string]int32{
		"AndroidVersion_NONE": 0,
		"V4_0":                15,
		"V4_1":                16,
		"V4_2":                17,
		"V4_3":                18,
		"V4_4":                19,
		"V4_4W":               20,
		"V5_0":                21,
		"V5_1":                22,
		"V6_0":                23,
		"V7_0":                24,
		"V7_1":                25,
		"V8_0":                26,
		"V8_1":                27,
		"V9_0":                28,
		"V10_0":               29,
		"V11_0":               30,
		"V12_0":               31,
	}
)

func (x AndroidVersion) Enum() *AndroidVersion {
	p := new(AndroidVersion)
	*p = x
	return p
}

func (x AndroidVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AndroidVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_android_proto_proto_enumTypes[0].Descriptor()
}

func (AndroidVersion) Type() protoreflect.EnumType {
	return &file_android_proto_proto_enumTypes[0]
}

func (x AndroidVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AndroidVersion.Descriptor instead.
func (AndroidVersion) EnumDescriptor() ([]byte, []int) {
	return file_android_proto_proto_rawDescGZIP(), []int{0}
}

type Architecture int32

const (
	Architecture_Architecture_NONE Architecture = 0
	Architecture_ARMEABI           Architecture = 1
	Architecture_ARM64             Architecture = 2
	Architecture_X86               Architecture = 3
	Architecture_X86_64            Architecture = 4
)

// Enum value maps for Architecture.
var (
	Architecture_name = map[int32]string{
		0: "Architecture_NONE",
		1: "ARMEABI",
		2: "ARM64",
		3: "X86",
		4: "X86_64",
	}
	Architecture_value = map[string]int32{
		"Architecture_NONE": 0,
		"ARMEABI":           1,
		"ARM64":             2,
		"X86":               3,
		"X86_64":            4,
	}
)

func (x Architecture) Enum() *Architecture {
	p := new(Architecture)
	*p = x
	return p
}

func (x Architecture) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Architecture) Descriptor() protoreflect.EnumDescriptor {
	return file_android_proto_proto_enumTypes[1].Descriptor()
}

func (Architecture) Type() protoreflect.EnumType {
	return &file_android_proto_proto_enumTypes[1]
}

func (x Architecture) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Architecture.Descriptor instead.
func (Architecture) EnumDescriptor() ([]byte, []int) {
	return file_android_proto_proto_rawDescGZIP(), []int{1}
}

type LocationProvider int32

const (
	LocationProvider_LocationProvider_NONE LocationProvider = 0 // Treat as random
	LocationProvider_GPS                   LocationProvider = 1
	LocationProvider_NETWORK               LocationProvider = 2
	LocationProvider_PASSIVE               LocationProvider = 3
)

// Enum value maps for LocationProvider.
var (
	LocationProvider_name = map[int32]string{
		0: "LocationProvider_NONE",
		1: "GPS",
		2: "NETWORK",
		3: "PASSIVE",
	}
	LocationProvider_value = map[string]int32{
		"LocationProvider_NONE": 0,
		"GPS":                   1,
		"NETWORK":               2,
		"PASSIVE":               3,
	}
)

func (x LocationProvider) Enum() *LocationProvider {
	p := new(LocationProvider)
	*p = x
	return p
}

func (x LocationProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocationProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_android_proto_proto_enumTypes[2].Descriptor()
}

func (LocationProvider) Type() protoreflect.EnumType {
	return &file_android_proto_proto_enumTypes[2]
}

func (x LocationProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocationProvider.Descriptor instead.
func (LocationProvider) EnumDescriptor() ([]byte, []int) {
	return file_android_proto_proto_rawDescGZIP(), []int{2}
}

type AndroidID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AndroidID) Reset() {
	*x = AndroidID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_android_proto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AndroidID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AndroidID) ProtoMessage() {}

func (x *AndroidID) ProtoReflect() protoreflect.Message {
	mi := &file_android_proto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AndroidID.ProtoReflect.Descriptor instead.
func (*AndroidID) Descriptor() ([]byte, []int) {
	return file_android_proto_proto_rawDescGZIP(), []int{0}
}

func (x *AndroidID) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GPSLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Longitude float64          `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude  float64          `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Altitude  float64          `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	Provider  LocationProvider `protobuf:"varint,4,opt,name=provider,proto3,enum=android_utils.LocationProvider" json:"provider,omitempty"`
}

func (x *GPSLocation) Reset() {
	*x = GPSLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_android_proto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPSLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPSLocation) ProtoMessage() {}

func (x *GPSLocation) ProtoReflect() protoreflect.Message {
	mi := &file_android_proto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPSLocation.ProtoReflect.Descriptor instead.
func (*GPSLocation) Descriptor() ([]byte, []int) {
	return file_android_proto_proto_rawDescGZIP(), []int{1}
}

func (x *GPSLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GPSLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GPSLocation) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *GPSLocation) GetProvider() LocationProvider {
	if x != nil {
		return x.Provider
	}
	return LocationProvider_LocationProvider_NONE
}

type Locale struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language   string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	CountryISO string `protobuf:"bytes,2,opt,name=countryISO,proto3" json:"countryISO,omitempty"`
}

func (x *Locale) Reset() {
	*x = Locale{}
	if protoimpl.UnsafeEnabled {
		mi := &file_android_proto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Locale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Locale) ProtoMessage() {}

func (x *Locale) ProtoReflect() protoreflect.Message {
	mi := &file_android_proto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Locale.ProtoReflect.Descriptor instead.
func (*Locale) Descriptor() ([]byte, []int) {
	return file_android_proto_proto_rawDescGZIP(), []int{2}
}

func (x *Locale) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Locale) GetCountryISO() string {
	if x != nil {
		return x.CountryISO
	}
	return ""
}

type SIMCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// With or without country code?
	PhoneNumber string `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	// Provider and country information
	MCC string `protobuf:"bytes,2,opt,name=MCC,proto3" json:"MCC,omitempty"`
	MNC string `protobuf:"bytes,3,opt,name=MNC,proto3" json:"MNC,omitempty"`
}

func (x *SIMCard) Reset() {
	*x = SIMCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_android_proto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SIMCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SIMCard) ProtoMessage() {}

func (x *SIMCard) ProtoReflect() protoreflect.Message {
	mi := &file_android_proto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SIMCard.ProtoReflect.Descriptor instead.
func (*SIMCard) Descriptor() ([]byte, []int) {
	return file_android_proto_proto_rawDescGZIP(), []int{3}
}

func (x *SIMCard) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SIMCard) GetMCC() string {
	if x != nil {
		return x.MCC
	}
	return ""
}

func (x *SIMCard) GetMNC() string {
	if x != nil {
		return x.MNC
	}
	return ""
}

type Timezone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// IANA standard
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Timezone) Reset() {
	*x = Timezone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_android_proto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Timezone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timezone) ProtoMessage() {}

func (x *Timezone) ProtoReflect() protoreflect.Message {
	mi := &file_android_proto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timezone.ProtoReflect.Descriptor instead.
func (*Timezone) Descriptor() ([]byte, []int) {
	return file_android_proto_proto_rawDescGZIP(), []int{4}
}

func (x *Timezone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Device struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                   *AndroidID     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Locale               *Locale        `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	Version              AndroidVersion `protobuf:"varint,3,opt,name=version,proto3,enum=android_utils.AndroidVersion" json:"version,omitempty"`
	Device               string         `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	Manufacturer         string         `protobuf:"bytes,5,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model                string         `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	Product              string         `protobuf:"bytes,7,opt,name=product,proto3" json:"product,omitempty"`
	Build                string         `protobuf:"bytes,8,opt,name=build,proto3" json:"build,omitempty"`
	Type                 string         `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	Tags                 string         `protobuf:"bytes,10,opt,name=tags,proto3" json:"tags,omitempty"`
	IncrementalVersion   string         `protobuf:"bytes,11,opt,name=incrementalVersion,proto3" json:"incrementalVersion,omitempty"`
	DPI                  int32          `protobuf:"varint,12,opt,name=DPI,proto3" json:"DPI,omitempty"`
	ResolutionHorizontal int32          `protobuf:"varint,13,opt,name=resolutionHorizontal,proto3" json:"resolutionHorizontal,omitempty"`
	ResolutionVertical   int32          `protobuf:"varint,14,opt,name=resolutionVertical,proto3" json:"resolutionVertical,omitempty"`
	Architecture         Architecture   `protobuf:"varint,15,opt,name=architecture,proto3,enum=android_utils.Architecture" json:"architecture,omitempty"`
	Location             *GPSLocation   `protobuf:"bytes,16,opt,name=location,proto3" json:"location,omitempty"`
	Timezone             *Timezone      `protobuf:"bytes,17,opt,name=timezone,proto3" json:"timezone,omitempty"`
	SimSlots             []*SIMCard     `protobuf:"bytes,18,rep,name=simSlots,proto3" json:"simSlots,omitempty"` // Dual SIM compatibility
}

func (x *Device) Reset() {
	*x = Device{}
	if protoimpl.UnsafeEnabled {
		mi := &file_android_proto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_android_proto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_android_proto_proto_rawDescGZIP(), []int{5}
}

func (x *Device) GetId() *AndroidID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Device) GetLocale() *Locale {
	if x != nil {
		return x.Locale
	}
	return nil
}

func (x *Device) GetVersion() AndroidVersion {
	if x != nil {
		return x.Version
	}
	return AndroidVersion_AndroidVersion_NONE
}

func (x *Device) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Device) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *Device) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Device) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *Device) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

func (x *Device) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Device) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *Device) GetIncrementalVersion() string {
	if x != nil {
		return x.IncrementalVersion
	}
	return ""
}

func (x *Device) GetDPI() int32 {
	if x != nil {
		return x.DPI
	}
	return 0
}

func (x *Device) GetResolutionHorizontal() int32 {
	if x != nil {
		return x.ResolutionHorizontal
	}
	return 0
}

func (x *Device) GetResolutionVertical() int32 {
	if x != nil {
		return x.ResolutionVertical
	}
	return 0
}

func (x *Device) GetArchitecture() Architecture {
	if x != nil {
		return x.Architecture
	}
	return Architecture_Architecture_NONE
}

func (x *Device) GetLocation() *GPSLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Device) GetTimezone() *Timezone {
	if x != nil {
		return x.Timezone
	}
	return nil
}

func (x *Device) GetSimSlots() []*SIMCard {
	if x != nil {
		return x.SimSlots
	}
	return nil
}

var File_android_proto_proto protoreflect.FileDescriptor

var file_android_proto_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x5f, 0x75,
	0x74, 0x69, 0x6c, 0x73, 0x22, 0x1b, 0x0a, 0x09, 0x41, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x49,
	0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x22, 0xa0, 0x01, 0x0a, 0x0b, 0x47, 0x50, 0x53, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61,
	0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x61,
	0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x61, 0x6e, 0x64, 0x72,
	0x6f, 0x69, 0x64, 0x5f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x22, 0x44, 0x0a, 0x06, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x53, 0x4f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x53, 0x4f, 0x22, 0x4f, 0x0a, 0x07, 0x53, 0x49,
	0x4d, 0x43, 0x61, 0x72, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x43, 0x43, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x43, 0x43, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x4e, 0x43,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x4e, 0x43, 0x22, 0x1e, 0x0a, 0x08, 0x54,
	0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xcc, 0x05, 0x0a, 0x06,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x5f, 0x75, 0x74, 0x69,
	0x6c, 0x73, 0x2e, 0x41, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x2d, 0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x5f, 0x75, 0x74, 0x69, 0x6c, 0x73,
	0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x52, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x12,
	0x37, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1d, 0x2e, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x5f, 0x75, 0x74, 0x69, 0x6c, 0x73,
	0x2e, 0x41, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x12, 0x2e, 0x0a, 0x12, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61,
	0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12,
	0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x44, 0x50, 0x49, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x44, 0x50, 0x49, 0x12, 0x32, 0x0a, 0x14, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x6f, 0x72, 0x69, 0x7a, 0x6f, 0x6e, 0x74, 0x61, 0x6c, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x14, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x6f,
	0x72, 0x69, 0x7a, 0x6f, 0x6e, 0x74, 0x61, 0x6c, 0x12, 0x2e, 0x0a, 0x12, 0x72, 0x65, 0x73, 0x6f,
	0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x12, 0x3f, 0x0a, 0x0c, 0x61, 0x72, 0x63, 0x68,
	0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b,
	0x2e, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x5f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x41,
	0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x0c, 0x61, 0x72, 0x63,
	0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x6e,
	0x64, 0x72, 0x6f, 0x69, 0x64, 0x5f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x47, 0x50, 0x53, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x33, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x11, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x5f, 0x75, 0x74,
	0x69, 0x6c, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x52, 0x08, 0x74, 0x69,
	0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x73, 0x69, 0x6d, 0x53, 0x6c, 0x6f,
	0x74, 0x73, 0x18, 0x12, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x6e, 0x64, 0x72, 0x6f,
	0x69, 0x64, 0x5f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x53, 0x49, 0x4d, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x08, 0x73, 0x69, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x2a, 0xd7, 0x01, 0x0a, 0x0e, 0x41,
	0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a,
	0x13, 0x41, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x56, 0x34, 0x5f, 0x30, 0x10, 0x0f,
	0x12, 0x08, 0x0a, 0x04, 0x56, 0x34, 0x5f, 0x31, 0x10, 0x10, 0x12, 0x08, 0x0a, 0x04, 0x56, 0x34,
	0x5f, 0x32, 0x10, 0x11, 0x12, 0x08, 0x0a, 0x04, 0x56, 0x34, 0x5f, 0x33, 0x10, 0x12, 0x12, 0x08,
	0x0a, 0x04, 0x56, 0x34, 0x5f, 0x34, 0x10, 0x13, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x34, 0x5f, 0x34,
	0x57, 0x10, 0x14, 0x12, 0x08, 0x0a, 0x04, 0x56, 0x35, 0x5f, 0x30, 0x10, 0x15, 0x12, 0x08, 0x0a,
	0x04, 0x56, 0x35, 0x5f, 0x31, 0x10, 0x16, 0x12, 0x08, 0x0a, 0x04, 0x56, 0x36, 0x5f, 0x30, 0x10,
	0x17, 0x12, 0x08, 0x0a, 0x04, 0x56, 0x37, 0x5f, 0x30, 0x10, 0x18, 0x12, 0x08, 0x0a, 0x04, 0x56,
	0x37, 0x5f, 0x31, 0x10, 0x19, 0x12, 0x08, 0x0a, 0x04, 0x56, 0x38, 0x5f, 0x30, 0x10, 0x1a, 0x12,
	0x08, 0x0a, 0x04, 0x56, 0x38, 0x5f, 0x31, 0x10, 0x1b, 0x12, 0x08, 0x0a, 0x04, 0x56, 0x39, 0x5f,
	0x30, 0x10, 0x1c, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x31, 0x30, 0x5f, 0x30, 0x10, 0x1d, 0x12, 0x09,
	0x0a, 0x05, 0x56, 0x31, 0x31, 0x5f, 0x30, 0x10, 0x1e, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x31, 0x32,
	0x5f, 0x30, 0x10, 0x1f, 0x2a, 0x52, 0x0a, 0x0c, 0x41, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41,
	0x52, 0x4d, 0x45, 0x41, 0x42, 0x49, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x52, 0x4d, 0x36,
	0x34, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x58, 0x38, 0x36, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06,
	0x58, 0x38, 0x36, 0x5f, 0x36, 0x34, 0x10, 0x04, 0x2a, 0x50, 0x0a, 0x10, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x15,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x50, 0x53, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x10, 0x02, 0x12, 0x0b, 0x0a,
	0x07, 0x50, 0x41, 0x53, 0x53, 0x49, 0x56, 0x45, 0x10, 0x03, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x52, 0x55, 0x48, 0x49, 0x74, 0x73,
	0x41, 0x42, 0x75, 0x6e, 0x6e, 0x79, 0x2f, 0x67, 0x6f, 0x2d, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69,
	0x64, 0x2d, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_android_proto_proto_rawDescOnce sync.Once
	file_android_proto_proto_rawDescData = file_android_proto_proto_rawDesc
)

func file_android_proto_proto_rawDescGZIP() []byte {
	file_android_proto_proto_rawDescOnce.Do(func() {
		file_android_proto_proto_rawDescData = protoimpl.X.CompressGZIP(file_android_proto_proto_rawDescData)
	})
	return file_android_proto_proto_rawDescData
}

var file_android_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_android_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_android_proto_proto_goTypes = []interface{}{
	(AndroidVersion)(0),   // 0: android_utils.AndroidVersion
	(Architecture)(0),     // 1: android_utils.Architecture
	(LocationProvider)(0), // 2: android_utils.LocationProvider
	(*AndroidID)(nil),     // 3: android_utils.AndroidID
	(*GPSLocation)(nil),   // 4: android_utils.GPSLocation
	(*Locale)(nil),        // 5: android_utils.Locale
	(*SIMCard)(nil),       // 6: android_utils.SIMCard
	(*Timezone)(nil),      // 7: android_utils.Timezone
	(*Device)(nil),        // 8: android_utils.Device
}
var file_android_proto_proto_depIdxs = []int32{
	2, // 0: android_utils.GPSLocation.provider:type_name -> android_utils.LocationProvider
	3, // 1: android_utils.Device.id:type_name -> android_utils.AndroidID
	5, // 2: android_utils.Device.locale:type_name -> android_utils.Locale
	0, // 3: android_utils.Device.version:type_name -> android_utils.AndroidVersion
	1, // 4: android_utils.Device.architecture:type_name -> android_utils.Architecture
	4, // 5: android_utils.Device.location:type_name -> android_utils.GPSLocation
	7, // 6: android_utils.Device.timezone:type_name -> android_utils.Timezone
	6, // 7: android_utils.Device.simSlots:type_name -> android_utils.SIMCard
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_android_proto_proto_init() }
func file_android_proto_proto_init() {
	if File_android_proto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_android_proto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AndroidID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_android_proto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPSLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_android_proto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Locale); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_android_proto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SIMCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_android_proto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Timezone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_android_proto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Device); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_android_proto_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_android_proto_proto_goTypes,
		DependencyIndexes: file_android_proto_proto_depIdxs,
		EnumInfos:         file_android_proto_proto_enumTypes,
		MessageInfos:      file_android_proto_proto_msgTypes,
	}.Build()
	File_android_proto_proto = out.File
	file_android_proto_proto_rawDesc = nil
	file_android_proto_proto_goTypes = nil
	file_android_proto_proto_depIdxs = nil
}
